name: KFA
main: com.j0ach1mmall3.kfa.Main
version: 1.0.0
author: j0ach1mmall3
description: Original KFA plugin for Minecraft! Be AFK as long as possible!d
depend: [Vault]
commands:
    KFA:
        description: Main KFA command
        usage: /<command> <arguments>
permissions:
    kfa.*:
        description: All the KFA permissions
        default: op
        children:
            kfa.reload: true
            kfa.bypass: true
    kfa.reload:
        description: Access to /kfa reload
        default: op
    kfa.bypass:
        description: Bypass all KFA checks
        default: op
        children:
            kfa.bypass.move: true
            kfa.bypass.look: true
            kfa.bypass.chat: true
            kfa.bypass.commands: true
    kfa.bypass.move:
        description: Allows you to bypass KFA move checks
        default: op
    kfa.bypass.look:
        description: Allows you to bypass KFA look checks
        default: op
    kfa.bypass.chat:
        description: Allows you to bypass KFA chat checks
        default: op
    kfa.bypass.commands:
        description: Allows you to bypass KFA commands checks
        default: op